- name: Ensure that our user has a home
  user:
    name: "{{ ssh_access_username }}"
    createhome: yes
    generate_ssh_key: yes

- file:
    path: "{{ ssh_access_private_key_path|dirname }}"
    state: directory
    owner: "{{ ssh_access_username }}"

- name: Ensure that we have SSH keys to propagate
  shell: "ssh-keygen -t rsa -f {{ ssh_access_private_key_path }} -N ''"
  args:
    creates: "{{ ssh_access_private_key_path }}"

- name: Change private key file permissions to allow next operation
  become: yes
  file:
    path: /home/performcoop/.ssh/id_rsa
    mode: 0644

- name: Read or pub key
  # http://askubuntu.com/a/53555
  shell: "ssh-keygen -y -f {{ ssh_access_private_key_path }}"
  register: current_ssh_pubkey
  changed_when: False

- name: Revert changes to private key file permissions
  become: yes
  file:
    path: /home/performcoop/.ssh/id_rsa
    mode: 0600

- set_fact: "ssh_access_public_key={{ current_ssh_pubkey.stdout }}"
  when: not ansible_check_mode

- debug: "msg={{ ssh_access_public_key }}"
  when: not ansible_check_mode
