---
- name: Ensure that target user exists
  user:
    name: "{{ current_target.username }}"
    shell: /bin/bash
  delegate_to: "{{ ssh_access_delegate_user }}@{{ current_target.host }}"
- name: Add pubkey to specified host
  authorized_key: "user={{ current_target.username }} key={{ ssh_access_public_key }}"
  delegate_to: "{{ ssh_access_delegate_user }}@{{ current_target.host }}"
  when: not ansible_check_mode
- name: Add extra pubkeys to specified host
  authorized_key: "user={{ current_target.username }} key={{ item }}"
  delegate_to: "{{ ssh_access_delegate_user }}@{{ current_target.host }}"
  with_items: "{{ ssh_access_extra_pubkeys|difference(['']) }}"
